<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AffectationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationRepository extends EntityRepository
{
    /**
     * Function to get the Team affectation joined to all the table in casacade
     */
    public function getTeamAffectation()
    {
        return $this->getRe->getEntityManager()
            ->createQueryBuilder()
            ->select('team')->from('AppBundle:Affectation', 'se')
            ->innerJoin('se.idSousEquipe', 'ssid')
            ->where('ssid = :user.');
        // TODO: Do how to retrive data


    }
}
