<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function existsByEmail($email)
    {
        $user = $this->findBy(['email' => $email]);
        return count($user) > 0;
    }
}
